# Generated by Django 5.1.3 on 2025-10-30 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('human_requested', models.BooleanField(default=False)),
                ('human_timeout_min', models.IntegerField(default=15)),
                ('human_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_in_at', models.DateTimeField(blank=True, null=True)),
                ('flow_node', models.CharField(blank=True, max_length=128, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_users', to='bots.bot')),
            ],
            options={
                'unique_together': {('bot', 'wa_id')},
            },
        ),
    ]
