# Generated by Django 5.1.3 on 2025-10-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_wauser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openrouter', 'OpenRouter')], default='openrouter', max_length=40)),
                ('name', models.CharField(blank=True, help_text='Etiqueta para identificar la clave', max_length=100)),
                ('api_key', models.TextField(help_text='Valor del API key (se guarda cifrado si el backend lo soporta)')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100, help_text='Menor número = mayor prioridad')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', '-is_active', 'last_used_at'],
            },
        ),
    ]
